export const useCases = {
    EDR: [
        { id: 'EDR_POWERSHELL_BASE64', title: 'Execution of PowerShell with Base64-Encoded Commands', severity: 'High', tags: ['Execution', 'Defense Evasion', 'T1059.001'] },
        { id: 'EDR_SUSPICIOUS_PARENT_CHILD', title: 'Suspicious Parent-Child Process Chain (e.g., Word → CMD → PowerShell)', severity: 'High', tags: ['Execution', 'T1059.001', 'T1204.002'] },
        { id: 'EDR_PROCESS_INJECTION', title: 'Process Injection Detected (e.g., into explorer.exe)', severity: 'Critical', tags: ['Defense Evasion', 'Privilege Escalation', 'T1055'] },
        { id: 'EDR_EXEC_FROM_SUSPICIOUS_PATH', title: 'Execution from Suspicious File Path (e.g., %Temp%)', severity: 'Medium', tags: ['Execution', 'T1204.002'] },
        { id: 'EDR_MIMIKATZ', title: 'Mimikatz Execution Detected on Endpoints', severity: 'Critical', tags: ['Credential Access', 'T1003.001'] },
        { id: 'EDR_UNKNOWN_HASH_MULTIPLE_ENDPOINTS', title: 'New or Unknown Hash Executed on Multiple Endpoints', severity: 'Medium', tags: ['Execution'] },
        { id: 'EDR_UNSIGNED_FROM_USB', title: 'Unsigned Executable Launched from Removable Media (USB)', severity: 'High', tags: ['Initial Access', 'T1200'] },
        { id: 'EDR_ENCODED_WMI_COMMAND', title: 'Encoded Command via WMI or WMIC Tool', severity: 'High', tags: ['Execution', 'T1047'] },
        { id: 'EDR_PERSISTENCE_AUTORUN', title: 'Persistence via Autorun Registry Key Modification', severity: 'Medium', tags: ['Persistence', 'T1547.001'] },
        { id: 'EDR_MASS_FILE_MODIFICATION', title: 'Abnormal Number of File Modifications by a Single Process (Ransomware)', severity: 'Critical', tags: ['Impact', 'T1486'] },
        { id: 'EDR_LOLBINS_EXECUTION', title: 'Execution of LOLBins (Living Off The Land Binaries)', severity: 'Medium', tags: ['Execution', 'Defense Evasion', 'T1218'] },
        { id: 'EDR_REMOTE_THREAD_INJECTION', title: 'Remote Thread Injection Between Two Processes', severity: 'High', tags: ['Defense Evasion', 'Privilege Escalation', 'T1055'] },
        { id: 'EDR_BEACONING_C2', title: 'Endpoint Beaconing to Rare External IP (C2 Communication)', severity: 'High', tags: ['Command and Control', 'T1071'] },
        { id: 'EDR_FILELESS_SCRIPT_LOAD', title: 'Malicious Script Loaded from Memory Only (Fileless Malware)', severity: 'High', tags: ['Defense Evasion', 'Execution', 'T1059'] },
        { id: 'EDR_LSASS_ACCESS', title: 'Access to LSASS Memory by Unauthorized Process', severity: 'Critical', tags: ['Credential Access', 'T1003.001'] },
        { id: 'EDR_BINARY_MASQUERADING', title: 'Binary Masquerading – .exe with Icon and Name of Word/PDF', severity: 'Medium', tags: ['Defense Evasion', 'T1036.005'] },
        { id: 'EDR_KNOWN_MALICIOUS_HASH', title: 'Known Malicious Hash Executed (Based on Threat Intel)', severity: 'Critical', tags: ['Execution', 'T1204.002'] },
        { id: 'EDR_RENAMED_EXECUTABLE', title: 'Executable Renamed to Evade Detection (e.g., mimikatz.exe → updater.exe)', severity: 'High', tags: ['Defense Evasion', 'T1036.003'] },
        { id: 'EDR_NEW_SERVICE_PERSISTENCE', title: 'New Service Created and Set to Auto-Start by Suspicious Process', severity: 'Medium', tags: ['Persistence', 'T1543.003'] },
        { id: 'EDR_UNEXPECTED_PARENT_PROCESS', title: 'Unexpected Parent Process for Sensitive Operations (e.g., explorer.exe launching net.exe)', severity: 'Medium', tags: ['Execution', 'T1059'] },
    ],
    DNS: [
        { id: 'DNS_KNOWN_MALICIOUS_DOMAIN', title: 'DNS Query to Known Malicious Domain or C2 Server', severity: 'High', tags: ['Command and Control', 'T1071.001'] },
        { id: 'DNS_HIGH_NXDOMAIN', title: 'High Volume of NXDOMAIN Responses from Single Host', severity: 'Medium', tags: ['Command and Control', 'Reconnaissance', 'T1595.002'] },
        { id: 'DNS_TXT_EXFILTRATION', title: 'DNS TXT Record Requests to Unusual Domains', severity: 'High', tags: ['Exfiltration', 'T1048.003'] },
        { id: 'DNS_DGA_ALGORITHM', title: 'Rapid DNS Requests for Multiple Subdomains (DGA)', severity: 'High', tags: ['Command and Control', 'T1568.002'] },
        { id: 'DNS_NON_STANDARD_PORT', title: 'Outbound DNS Queries Over Non-Standard Ports', severity: 'Medium', tags: ['Command and Control', 'Defense Evasion', 'T1071'] },
        { id: 'DNS_NEWLY_REGISTERED_DOMAIN', title: 'DNS Request for Newly Registered or Rare Domains', severity: 'Medium', tags: ['Command and Control', 'T1583.001'] },
    ],
    O365: [
        { id: 'O365_FAILED_LOGINS_UNUSUAL_LOCATION', title: 'Multiple Failed Login Attempts from Unusual Locations', severity: 'Medium', tags: ['Initial Access', 'T1110'] },
        { id: 'O365_MALICIOUS_ATTACHMENT', title: 'Email Received with Malicious Attachments', severity: 'High', tags: ['Initial Access', 'T1566.001'] },
        { id: 'O365_UNUSUAL_FORWARDING_RULE', title: 'Unusual Email Forwarding Rules Set by User', severity: 'High', tags: ['Collection', 'Exfiltration', 'T1114.003'] },
        { id: 'O365_SIGNIN_FROM_NEW_DEVICE', title: 'Sign-in from Device or IP Not Seen Before', severity: 'Medium', tags: ['Initial Access', 'T1078'] },
    ],
    AD: [
        { id: 'AD_KERBEROS_BRUTE_FORCE', title: 'Multiple Failed Kerberos Ticket Requests for Single Account', severity: 'Medium', tags: ['Credential Access', 'T1110.003'] },
        { id: 'AD_NEW_DOMAIN_ADMIN', title: 'New Domain Admin Account Created Outside Maintenance Window', severity: 'Critical', tags: ['Persistence', 'Privilege Escalation', 'T1098'] },
        { id: 'AD_PASSTHEHASH', title: 'Use of Pass-the-Ticket or Pass-the-Hash Techniques Detected', severity: 'Critical', tags: ['Lateral Movement', 'T1550.002'] },
        { id: 'AD_GOLDEN_TICKET', title: 'Suspicious Kerberos Golden Ticket Usage', severity: 'Critical', tags: ['Credential Access', 'Persistence', 'T1558.001'] },
    ],
    DLP: [
        { id: 'DLP_SENSITIVE_FILES_CLOUD_UPLOAD', title: 'Sensitive Files Uploaded to Unauthorized Cloud Storage', severity: 'High', tags: ['Exfiltration', 'T1537'] },
        { id: 'DLP_COPY_TO_USB', title: 'Copying of Sensitive Documents to USB Drives', severity: 'High', tags: ['Exfiltration', 'T1052.001'] },
        { id: 'DLP_MASS_DOWNLOAD_CONFIDENTIAL', title: 'Mass Download of Confidential Data from Internal File Shares', severity: 'High', tags: ['Collection', 'T1074'] },
    ],
    Azure: [
        { id: 'AZURE_SUSPICIOUS_LOGIN', title: 'Suspicious Login from Unfamiliar IP or Country', severity: 'Medium', tags: ['Initial Access', 'T1078'] },
        { id: 'AZURE_PRIVILEGE_ELEVATION', title: 'Elevation of Privileges via Role Assignment Changes', severity: 'Critical', tags: ['Privilege Escalation', 'T1078'] },
        { id: 'AZURE_MASS_BLOB_DELETION', title: 'Mass Deletion or Modification of Azure Storage Blobs', severity: 'Critical', tags: ['Impact', 'T1485'] },
        { id: 'AZURE_HIGH_DATA_TRANSFER', title: 'Abnormal Data Transfer Volume in Azure Blob Storage', severity: 'High', tags: ['Exfiltration', 'T1048'] },
    ],
    AWS: [
        { id: 'AWS_SUSPICIOUS_CONSOLE_LOGIN', title: 'Suspicious Console Login from Unusual IP or Location', severity: 'Medium', tags: ['Initial Access', 'T1078'] },
        { id: 'AWS_ADMIN_IAM_USER_CREATION', title: 'Creation of IAM User with Administrator Privileges', severity: 'Critical', tags: ['Privilege Escalation', 'T1098'] },
        { id: 'AWS_CLOUDTRAIL_DELETION', title: 'Modification or Deletion of CloudTrail Logs', severity: 'Critical', tags: ['Defense Evasion', 'T1562.008'] },
        { id: 'AWS_HIGH_VOLUME_S3_TRANSFER', title: 'High Volume Data Transfer from S3 Buckets to External IPs', severity: 'High', tags: ['Exfiltration', 'T1048'] },
    ],
    Email: [
        { id: 'EMAIL_BEC_WIRE_TRANSFER', title: 'Business Email Compromise — Fraudulent Wire Transfer via Spoofed CFO', severity: 'Critical', tags: ['Initial Access', 'Fraud', 'T1566.002', 'BEC'] },
        { id: 'EMAIL_QR_CODE_PHISHING', title: 'QR Code Phishing Bypassing URL Security Filters', severity: 'High', tags: ['Initial Access', 'T1566.001', 'QRishing'] },
        { id: 'EMAIL_HTML_SMUGGLING', title: 'HTML Smuggling via Email Attachment Delivering Infostealer', severity: 'High', tags: ['Initial Access', 'Defense Evasion', 'T1027.006', 'T1566.001'] },
        { id: 'EMAIL_CALLBACK_PHISHING', title: 'Callback Phishing (TOAD) — Fake Subscription Invoice with Toll-Free Number', severity: 'Medium', tags: ['Initial Access', 'T1566', 'Social Engineering'] },
        { id: 'EMAIL_SPEARPHISHING_MACRO', title: 'Spearphishing Attachment — Malicious Macro Delivering IcedID/Latrodectus', severity: 'High', tags: ['Initial Access', 'T1566.001', 'T1204.002'] },
        { id: 'EMAIL_DMARC_FAIL_SPOOF', title: 'Email Spoofing — DMARC Failure on Trusted Domain Impersonation', severity: 'Medium', tags: ['Initial Access', 'Defense Evasion', 'T1566'] },
        { id: 'EMAIL_ISO_LNK_DELIVERY', title: 'Malware Delivery via ISO / LNK File to Bypass Mark-of-the-Web', severity: 'High', tags: ['Initial Access', 'Defense Evasion', 'T1566.001', 'T1553.005'] },
        { id: 'EMAIL_BEC_FORWARDING_RULE', title: 'Auto-Forwarding Rule Created Following BEC Account Compromise', severity: 'High', tags: ['Collection', 'Exfiltration', 'T1114.003'] },
    ],
    DNS: [
        { id: 'DNS_KNOWN_MALICIOUS_DOMAIN', title: 'DNS Query to Known Malicious Domain or C2 Server', severity: 'High', tags: ['Command and Control', 'T1071.001'] },
        { id: 'DNS_HIGH_NXDOMAIN', title: 'High Volume of NXDOMAIN Responses from Single Host', severity: 'Medium', tags: ['Command and Control', 'Reconnaissance', 'T1595.002'] },
        { id: 'DNS_TXT_EXFILTRATION', title: 'DNS TXT Record Requests Encoding Exfiltrated Data', severity: 'High', tags: ['Exfiltration', 'T1048.003'] },
        { id: 'DNS_DGA_ALGORITHM', title: 'DGA — High-Entropy Algorithmically Generated Domain Queries', severity: 'High', tags: ['Command and Control', 'T1568.002'] },
        { id: 'DNS_TUNNELING_SUBDOMAIN', title: 'DNS Tunneling — Base64-Encoded Data in Oversized Subdomain Labels', severity: 'Critical', tags: ['Exfiltration', 'Command and Control', 'T1048.003', 'T1071.004'] },
        { id: 'DNS_NON_STANDARD_PORT', title: 'Outbound DNS Queries Over Non-Standard Ports (5353, 8053)', severity: 'Medium', tags: ['Command and Control', 'Defense Evasion', 'T1071'] },
        { id: 'DNS_NEWLY_REGISTERED_DOMAIN', title: 'DNS Request for Newly Registered Phishing Domain (< 30 days)', severity: 'Medium', tags: ['Command and Control', 'T1583.001'] },
        { id: 'DNS_C2_BEACON_PATTERN', title: 'Regular-Interval DNS Beaconing to Rare External Domain (C2)', severity: 'High', tags: ['Command and Control', 'T1071.004'] },
    ],
    CTF: [
        { id: 'CTF_DNS_TUNNEL_EXFIL', title: 'Silent Exfil: Find the Data Exfiltrated via DNS Tunneling', severity: 'Hard', tags: ['Exfiltration', 'T1048.003', 'CTF'] },
        { id: 'CTF_PHANTOM_ADMIN', title: 'The Phantom Admin: Golden Ticket Abuse in AD Logs', severity: 'Advanced', tags: ['Lateral Movement', 'Persistence', 'T1558.001', 'CTF'] },
        { id: 'CTF_C2_BEACON_INTERVAL', title: 'Invisible Beacon: Identify the C2 Beacon Interval', severity: 'Advanced', tags: ['Command and Control', 'T1071', 'CTF'] },
        { id: 'CTF_REGISTRY_PERSISTENCE', title: 'Ghost in the Registry: Hidden Persistence Mechanism', severity: 'Intermediate', tags: ['Persistence', 'T1547.001', 'CTF'] },
        { id: 'CTF_SUPPLY_CHAIN', title: 'Supply Chain Smoke: ISO Delivery Kill Chain', severity: 'Expert', tags: ['Initial Access', 'Supply Chain', 'CTF'] },
        { id: 'CTF_LOCKBIT_STAGING', title: 'LockBit Prelude: Ransomware Staging via LOLBins', severity: 'Advanced', tags: ['Impact', 'Defense Evasion', 'T1486', 'CTF'] },
        { id: 'CTF_KERBEROAST', title: 'Kerberoast Season: SPN Scanning and Hash Extraction', severity: 'Intermediate', tags: ['Credential Access', 'T1558.003', 'CTF'] },
        { id: 'CTF_BEC_HEIST', title: 'BEC Heist: Azure AD Token Theft for Wire Fraud', severity: 'Intermediate', tags: ['Initial Access', 'BEC', 'T1528', 'CTF'] },
        { id: 'CTF_LIVING_GHOST', title: 'The Living Ghost: Fileless PowerShell via WMI', severity: 'Advanced', tags: ['Defense Evasion', 'Execution', 'T1047', 'T1059.001', 'CTF'] },
        { id: 'CTF_SHADOW_IT_AWS', title: 'Shadow IT AWS: Unauthorized IAM Creation and S3 Exfil', severity: 'Intermediate', tags: ['Privilege Escalation', 'Exfiltration', 'T1098', 'CTF'] },
    ],
};